export 
const tableData = [
  {
    id: 1,
    name: "Daniel",
    lastName: "Brito",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 2,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 3,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 4,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 5,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 6,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 7,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 8,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 9,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 10,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 11,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 12,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 13,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 14,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 15,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 16,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 17,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 18,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 19,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 20,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 21,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 22,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 23,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 24,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 25,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  }, {
    id: 26,
    name: "Daniel",
    lastName: "Brito",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 27,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 28,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 29,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 30,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 31,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 32,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 33,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 34,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 35,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 36,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 37,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 38,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 39,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 40,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 41,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 42,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 43,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 44,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 45,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 46,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 47,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 48,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 49,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 50,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 51,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 52,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 53,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 54,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 55,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 56,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 57,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 58,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 59,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 60,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 61,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 62,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 63,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 64,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 65,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 66,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 67,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 68,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 69,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 70,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 71,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 72,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 73,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 74,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 75,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 76,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 77,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 78,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 79,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 80,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 81,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 82,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 83,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 84,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 85,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 86,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 87,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 88,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 89,
    name: "John",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 90,
    name: "Jane",
    lastName: "Smith",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 91,
    name: "John",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
  {
    id: 92,
    name: "Jane",
    lastName: "Doe",
    employeeNumber: "123456",
    email: "daniel@gmail.com",
    phone: "1234567890",
    department: "IT",
    jobTitle: "Software Engineer",
    location: "San Diego",
    hireDate: "2021-01-01",
    terminationDate: "2021-01-01",
    status: "Active",
    payType: "Salary",
    payRate: "100000",
    payFrequency: "Yearly",
  },
    {
        id: 93,
        name: "John",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 94,
        name: "Jane",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 95,
        name: "John",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 96,
        name: "Jane",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 97,
        name: "John",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 98,
        name: "Jane",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 99,
        name: "John",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 100,
        name: "Jane",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 101,
        name: "John",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 102,
        name: "Jane",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 103,
        name: "John",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 104,
        name: "Jane",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 105,
        name: "John",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 106,
        name: "Jane",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 107,
        name: "John",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 108,
        name: "Jane",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 109,
        name: "John",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 110,
        name: "Jane",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 111,
        name: "John",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 112,
        name: "Jane",
        lastName: "Doe",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 113,
        name: "John",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    },
    {
        id: 114,
        name: "Jane",
        lastName: "Smith",
        employeeNumber: "123456",
        email: "daniel@gmail.com",
        phone: "1234567890",
        department: "IT",
        jobTitle: "Software Engineer",
        location: "San Diego",
        hireDate: "2021-01-01",
        terminationDate: "2021-01-01",
        status: "Active",
        payType: "Salary",
        payRate: "100000",
        payFrequency: "Yearly",
    }
];